# ==========================================
# 1. REDIRECCIÓN HTTP -> HTTPS (PUERTO 80)
# ==========================================
server {
    listen 80;
    server_name bpmn-soft.duckdns.org;
    
    # Todo el que entre sin seguridad, es redirigido al candado verde
    return 301 https://$host$request_uri;
}

# ==========================================
# 2. SERVIDOR PRINCIPAL SEGURO (PUERTO 443)
# ==========================================
server {
    listen 443 ssl;
    server_name bpmn-soft.duckdns.org;

    # Rutas de los certificados inyectados por Docker
    ssl_certificate /etc/letsencrypt/live/bpmn-soft.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/bpmn-soft.duckdns.org/privkey.pem;

    # Configuraciones de seguridad extra
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # Tu configuración original intacta
    client_max_body_size 50M;
    root /usr/share/nginx/html;
    index index.html;

    # Frontend (Angular)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Backend (API REST)
    location /api/ {
        proxy_pass http://backend:8080/api/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Backend (GraphQL)
    location /graphql {
        proxy_pass http://backend:8080/graphql;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Backend (WebSockets para el Diseñador BPMN)
    location /ws-designer {
        proxy_pass http://backend:8080/ws-designer;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_read_timeout 3600;
    }
}